### ISSUE TITLE
Error Handling on Vote tab - bad vote

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#899] opened 2022-02-23 03:50 UTC
Sometimes, a proposal can have a bug in the smart contract. The frontend should filter bad proposals out of the UI to avoid crashing

<img width="1169" alt="Screen Shot 2022-02-22 at 7 49 31 PM" src="https://user-images.githubusercontent.com/43685868/155258819-f13244ef-08e1-47e0-a5b3-81b4c1b4989a.png">

<img width="1049" alt="Screen Shot 2022-02-22 at 7 48 18 PM" src="https://user-images.githubusercontent.com/43685868/155258749-62102794-db85-4309-ad50-598e772e691e.png">

**Comment by shallcdn** [comment] 2022-02-26 11:56
Hi @BennyOptions  I have investigated this issue, this is not a crash proposal, this screen as you see is a loading screen of Vote Page.

Issue's root cause is the API of smart contract return error and has no any records, so that FE doesn't have any record to filter and display on UI, that why you see the loading screen as above.

**Comment by BennyOptions** [comment] 2022-03-03 05:36
Hey @shallcdn - let me explain, I believe there is some confusion.

First thing to mention, this is a minor issue. I adjusted the label to p2 so we can instead focus on other issues. But to explain, the goal is to get the FE to errorHandle in the situation where there is an issue with one proposal on the smart contract. With the current FE logic, one bad proposal can break the FE. If there is a bad proposal, ideally, the FE will simply hide the bad proposal rather than break. I am not a developer, but I tend to think the logic to errorHandle for this situation would be fairly complex and possibly not worth the effort.

Let me know what you think, maybe we can close the issue.

**Comment by shallcdn** [comment] 2022-03-03 07:55
Hi @BennyOptions, I got your point, so let me explain a bit about the currently logic of the Vote page to make us have a same view

- You will see the screen as the image above when you direct to the Vote Page even though it has a lousy proposal or not.

    - If we don't have a lousy proposal, you will wait a bit, the API `getProposals` of the smart contract will return a list of proposals, and the proposals will appear like normal
    
    - If we have a terrible proposal, the API `getProposals` of the smart contract will retrieve an error (not a list of proposals that include a flawed proposal) => that's why FE cannot filter and show them as your suggestion.
    
To do as you want, we need to edit the smart contract that has `getProposals` API, change logic from throwing an error to returning a list of proposals, including the lousy proposal, and then FE will update logic to adapt with that changing. It's so easy for FE.

=> I think updating the logic of smart contract is complicated and take time. So I think we should close this issue

**Closed** 2022-07-06 02:51 UTC
Labels: p2, api-integration
